### ISSUE TITLE
Spacing between result groups

### ISSUE THREAD

**Issue by qdacsvx** [youcongress/youcongress#105]
Strongly Agree:Agree / Abstain:NA / Disagree:Strongly Disagree

/=spacing

separating the groups would show (by the size of the group) the strength of each group.

**Comment by hectorperez** [comment]
I'm not sure how it will look like, but it's worth to give it a try.

**Comment by qdacsvx** [comment]
The size of the groups is proportional to the number of votes. It might be counter-intuitive that strong agreement counts the same as mere agreement.

**Comment by hectorperez** [comment]
@qdacsvx I added the spacing:

- Added black vertical bar between:
  - Strongly agree and Agree
  - Neutral and N/A
  - Agree and Strongly Agree
- Added white vertical bar between:
  - Strongly Agree/Agree and Neutral/N/A
  - Neutral/N/A and Disagree/Strongly disagree

Let me know if you have any comment.

> It might be counter-intuitive that strong agreement counts the same as mere agreement.

But, at the same time, one-vote per person seems intuitive, isn't it?

Thanks for the feedback!

**Comment by hectorperez** [comment]
> It might be counter-intuitive that strong agreement counts the same as mere agreement.

@qdacsvx I thought one-vote per person seemed intuitive. But now I'm not sure.
How much more do you think a strong agreement should count? Twice?

**Comment by qdacsvx** [comment]
I'm not sure about using a black bar between disagree and strong disagree. I'd prefer to use the same separator (white) as between agree and strong agree.

Using a black bar makes the votes (disagree, strong disagree) seem to be a group: using a white bar separates the votes (agree, strong agree) emphasising that different votes represent different opinions.

I like one person per vote linear representation but it could be misleading e.g. suppose that 40% strong agree but 55% disagree: by linear votes, there is a majority for disagreement, but by (weight of) opinion there is likely a preference for agreement if the mean value of strong agreement is above 55/40 (~114%) compared to the mean value of disagreement.

Showing each type of vote as a separate bar (on a new line) would allow to compare the proportions of each choice.

**Comment by hectorperez** [comment]
When you wrote "Strongly Agree:Agree / Abstain:NA / Disagree:Strongly Disagree" I thought you meant to differentiate the separation between Strongly Agree and Agree differently than from Agree and Abstain. Which I'd it make sense, although I don't have a strong opinion on this. Do you think the same separation (white) between all options is better?

Regarding having a separate bar/line per option, we had that some time ago. But it took too much space in the page so I changed it. Maybe there's a way not to use so much screen real state, but not sure how at the moment.
