### ISSUE TITLE
User search

### ISSUE THREAD

**Issue by qdacsvx** [youcongress/youcongress#107]
There are many famous delegates I would like to follow but how can I find them?

**Comment by hectorperez** [comment]
You're right, we need this!

Until a proper search is done, a cumbersome solution is to find their username on X/Twitter and go to youcongress.com/x/twitter_username I know this is not a good solution, but until I or someone else can work on this, it might help.

Thanks for the issue!

**Comment by hectorperez** [comment]
@qdacsvx I added an input in the [home page](https://youcongress.com) to search polls and delegates:

<img width="468" alt="Screenshot 2024-10-06 at 15 52 58" src="https://github.com/user-attachments/assets/452fd40a-ef1a-4fa5-b9f1-2e74f17eaf7e">

Let me know if you try it!

**Comment by hectorperez** [comment]
That’s a good idea. Yet, most of Twitter’s API requires to pay at least 100€/month. I’d prefer delaying it until we have more resources or users. However, if we did, then we could get the pictures of the delegates and the list of people that our users follow (to recommend them delegates). We could also use Twitter lists to discover people and even to delegate to a whole list.

What you can do right now is to add a real quote of Wei Dai from a poll page (click on “real quotes”) at the top of the page. Then, you can delegate:

![IMG_0086](https://github.com/user-attachments/assets/b1b757ab-2dee-4552-ba55-e08ac2d1f766)

**Comment by hectorperez** [comment]
I'm closing this issue as the general user search is done.
We may open another for searching any twitter user or person on Wikipedia.
