### ISSUE TITLE
Equal size voting choices

### ISSUE THREAD

**Issue by qdacsvx** [youcongress/youcongress#122]
If the voting buttons are not an equal size it suggests that some choices are less important or less appropriate.

**Comment by hectorperez** [comment]
Done, thanks!

By the way, if you haven't seen it, now we can also vote from the home page. Let me know what you think!

**Comment by qdacsvx** [comment]
Voting from the front page is nice. I half think there should be more notice that the icons are for voting like a "Vote:" label before the options.

**Comment by hectorperez** [comment]
We'll need to think about that. Something related I'm not sure is whether we should keep one opinion under the buttons of each poll in the home page. Or if we should only have titles + buttons.

By the way, the displayed opinion under the title/buttons of a poll in the home page is the most liked one. At least at the moment. In case you'd like to like some good ones.
